# .github/workflows/lint.yml
name: Code Lint

on:
  push:
    paths: ["src/**"]
    branches:
      - '**'        # 所有分支推送都会触发
  pull_request:
    branches:
      - master     # 针对 master 分支的 PR 会触发

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python: [3.10,3.11,3.12]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}

      - name: Install lint tools
        run: |
          python -m pip install --upgrade pip
          pip install black flake8

      - name: Black format check
        run: black --check src

      - name: Flake8 static analysis
        run: flake8 src
